services:
  - type: web
    name: jimenez-flight-dashboard
    rootDir: tarea-dash Jimenez Pedro
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard:server --bind 0.0.0.0:$PORT
    healthCheckPath: /
    autoDeployTrigger: commit
